/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AboutImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as SignUpSplatImport } from './routes/sign-up.$'
import { Route as SignInSplatImport } from './routes/sign-in.$'
import { Route as DashboardOrganizationImport } from './routes/dashboard/organization'
import { Route as DashboardPoliciesIndexImport } from './routes/dashboard/policies/index'
import { Route as DashboardContactsIndexImport } from './routes/dashboard/contacts/index'
import { Route as DashboardPoliciesUpdateImport } from './routes/dashboard/policies/update'
import { Route as DashboardPoliciesCreateImport } from './routes/dashboard/policies/create'
import { Route as DashboardPoliciesPolicyIdImport } from './routes/dashboard/policies/$policyId'
import { Route as DashboardOrganizationSplatImport } from './routes/dashboard/organization.$'
import { Route as DashboardContactsContactIdImport } from './routes/dashboard/contacts/$contactId'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const SignUpSplatRoute = SignUpSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)

const SignInSplatRoute = SignInSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)

const DashboardOrganizationRoute = DashboardOrganizationImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPoliciesIndexRoute = DashboardPoliciesIndexImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardContactsIndexRoute = DashboardContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPoliciesUpdateRoute = DashboardPoliciesUpdateImport.update({
  id: '/policies/update',
  path: '/policies/update',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPoliciesCreateRoute = DashboardPoliciesCreateImport.update({
  id: '/policies/create',
  path: '/policies/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPoliciesPolicyIdRoute = DashboardPoliciesPolicyIdImport.update({
  id: '/policies/$policyId',
  path: '/policies/$policyId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardOrganizationSplatRoute = DashboardOrganizationSplatImport.update(
  {
    id: '/$',
    path: '/$',
    getParentRoute: () => DashboardOrganizationRoute,
  } as any,
)

const DashboardContactsContactIdRoute = DashboardContactsContactIdImport.update(
  {
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/organization': {
      id: '/dashboard/organization'
      path: '/organization'
      fullPath: '/dashboard/organization'
      preLoaderRoute: typeof DashboardOrganizationImport
      parentRoute: typeof DashboardRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatImport
      parentRoute: typeof SignInImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatImport
      parentRoute: typeof SignUpImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/contacts/$contactId': {
      id: '/dashboard/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/dashboard/contacts/$contactId'
      preLoaderRoute: typeof DashboardContactsContactIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/organization/$': {
      id: '/dashboard/organization/$'
      path: '/$'
      fullPath: '/dashboard/organization/$'
      preLoaderRoute: typeof DashboardOrganizationSplatImport
      parentRoute: typeof DashboardOrganizationImport
    }
    '/dashboard/policies/$policyId': {
      id: '/dashboard/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/dashboard/policies/$policyId'
      preLoaderRoute: typeof DashboardPoliciesPolicyIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/policies/create': {
      id: '/dashboard/policies/create'
      path: '/policies/create'
      fullPath: '/dashboard/policies/create'
      preLoaderRoute: typeof DashboardPoliciesCreateImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/policies/update': {
      id: '/dashboard/policies/update'
      path: '/policies/update'
      fullPath: '/dashboard/policies/update'
      preLoaderRoute: typeof DashboardPoliciesUpdateImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/policies/': {
      id: '/dashboard/policies/'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardOrganizationRouteChildren {
  DashboardOrganizationSplatRoute: typeof DashboardOrganizationSplatRoute
}

const DashboardOrganizationRouteChildren: DashboardOrganizationRouteChildren = {
  DashboardOrganizationSplatRoute: DashboardOrganizationSplatRoute,
}

const DashboardOrganizationRouteWithChildren =
  DashboardOrganizationRoute._addFileChildren(
    DashboardOrganizationRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardOrganizationRoute: typeof DashboardOrganizationRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContactsContactIdRoute: typeof DashboardContactsContactIdRoute
  DashboardPoliciesPolicyIdRoute: typeof DashboardPoliciesPolicyIdRoute
  DashboardPoliciesCreateRoute: typeof DashboardPoliciesCreateRoute
  DashboardPoliciesUpdateRoute: typeof DashboardPoliciesUpdateRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardPoliciesIndexRoute: typeof DashboardPoliciesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrganizationRoute: DashboardOrganizationRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContactsContactIdRoute: DashboardContactsContactIdRoute,
  DashboardPoliciesPolicyIdRoute: DashboardPoliciesPolicyIdRoute,
  DashboardPoliciesCreateRoute: DashboardPoliciesCreateRoute,
  DashboardPoliciesUpdateRoute: DashboardPoliciesUpdateRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardPoliciesIndexRoute: DashboardPoliciesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard/organization': typeof DashboardOrganizationRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/organization/$': typeof DashboardOrganizationSplatRoute
  '/dashboard/policies/$policyId': typeof DashboardPoliciesPolicyIdRoute
  '/dashboard/policies/create': typeof DashboardPoliciesCreateRoute
  '/dashboard/policies/update': typeof DashboardPoliciesUpdateRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/policies': typeof DashboardPoliciesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard/organization': typeof DashboardOrganizationRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/organization/$': typeof DashboardOrganizationSplatRoute
  '/dashboard/policies/$policyId': typeof DashboardPoliciesPolicyIdRoute
  '/dashboard/policies/create': typeof DashboardPoliciesCreateRoute
  '/dashboard/policies/update': typeof DashboardPoliciesUpdateRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/policies': typeof DashboardPoliciesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard/organization': typeof DashboardOrganizationRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/organization/$': typeof DashboardOrganizationSplatRoute
  '/dashboard/policies/$policyId': typeof DashboardPoliciesPolicyIdRoute
  '/dashboard/policies/create': typeof DashboardPoliciesCreateRoute
  '/dashboard/policies/update': typeof DashboardPoliciesUpdateRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/policies/': typeof DashboardPoliciesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/organization'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/organization/$'
    | '/dashboard/policies/$policyId'
    | '/dashboard/policies/create'
    | '/dashboard/policies/update'
    | '/dashboard/contacts'
    | '/dashboard/policies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/organization'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/organization/$'
    | '/dashboard/policies/$policyId'
    | '/dashboard/policies/create'
    | '/dashboard/policies/update'
    | '/dashboard/contacts'
    | '/dashboard/policies'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/organization'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/organization/$'
    | '/dashboard/policies/$policyId'
    | '/dashboard/policies/create'
    | '/dashboard/policies/update'
    | '/dashboard/contacts/'
    | '/dashboard/policies/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/about",
        "/sign-in",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/organization",
        "/dashboard/",
        "/dashboard/contacts/$contactId",
        "/dashboard/policies/$policyId",
        "/dashboard/policies/create",
        "/dashboard/policies/update",
        "/dashboard/contacts/",
        "/dashboard/policies/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx",
      "children": [
        "/sign-in/$"
      ]
    },
    "/sign-up": {
      "filePath": "sign-up.tsx",
      "children": [
        "/sign-up/$"
      ]
    },
    "/dashboard/organization": {
      "filePath": "dashboard/organization.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/organization/$"
      ]
    },
    "/sign-in/$": {
      "filePath": "sign-in.$.tsx",
      "parent": "/sign-in"
    },
    "/sign-up/$": {
      "filePath": "sign-up.$.tsx",
      "parent": "/sign-up"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/contacts/$contactId": {
      "filePath": "dashboard/contacts/$contactId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/organization/$": {
      "filePath": "dashboard/organization.$.tsx",
      "parent": "/dashboard/organization"
    },
    "/dashboard/policies/$policyId": {
      "filePath": "dashboard/policies/$policyId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/policies/create": {
      "filePath": "dashboard/policies/create.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/policies/update": {
      "filePath": "dashboard/policies/update.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/contacts/": {
      "filePath": "dashboard/contacts/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/policies/": {
      "filePath": "dashboard/policies/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
